### ISSUE TITLE
xdebug.ini for xdebug 3 / php 8.1

### ISSUE THREAD

**Issue by herberlin** [mobtitude/docker-php-xdebug#4]
Images using xdebug 3 must use the new configuration parameters as said in the xdebug configuration; for me the following file worked fine:

xdebug.ini
---------------
```
zend_extension=xdebug
[xdebug]
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.start_with_request=yes
```

When working with docker compose you'll need a so called extra_host - mapping for the internal gateway. Working for me: 

docker-compose.yml
---
```yml
  php:
    container_name: apache_php
    # image: mobtitude/php-xdebug:8.1-apache
    build: docker/apache2/build
    ports:
      - 8080:80
      - 9001:9003
    volumes:
      [...]
    extra_hosts:
      - host.docker.internal:host-gateway
```

In the `docker/apache2/build` I placed your `Dockerfile` and the `xdebug.ini` as shown above.

Thank you very much for sharing and 
cheers 
Achim
